name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # 매일 아침 7시 (UTC)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        
      - name: Run scraper
        run: |
          export DISPLAY=:99
          sudo Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          python newbooks.py

      - name: Save deployment time
        run: |
          echo "{\"last_deploy\": \"$(TZ='Asia/Seoul' date '+%Y년 %m월 %d일 %H:%M')\"}" > deploy_info.json
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 